version: '3.1'
services:
  web:
    image: odoo:13
    depends_on:
      - mydb
    ports:
      - "5013:8070"
    volumes:
      - odoo13-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo13-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo13-web-data:
  odoo13-db-data:
